<?php
use Migrations\AbstractSeed;

/**
 * DigitalDetails seed.
 */
class DigitalDetailsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'digital_id' => '1',
                'name' => 'Axis Rp 5.000',
                'denom' => '5000',
                'operator' => 'Axis',
                'price' => '5930',
                'status' => '0',
            ],
            [
                'id' => '2',
                'digital_id' => '1',
                'name' => 'Axis Rp 10.000',
                'denom' => '10000',
                'operator' => 'Axis',
                'price' => '11250',
                'status' => '0',
            ],
            [
                'id' => '3',
                'digital_id' => '1',
                'name' => 'Axis Rp 15.000',
                'denom' => '15000',
                'operator' => 'Axis',
                'price' => '15350',
                'status' => '0',
            ],
            [
                'id' => '4',
                'digital_id' => '1',
                'name' => 'Axiata Axis Rp 25.000',
                'denom' => '25000',
                'operator' => 'Axis',
                'price' => '24850',
                'status' => '0',
            ],
            [
                'id' => '5',
                'digital_id' => '1',
                'name' => 'Axis Rp 30.000',
                'denom' => '30000',
                'operator' => 'Axis',
                'price' => '29700',
                'status' => '0',
            ],
            [
                'id' => '6',
                'digital_id' => '1',
                'name' => 'Axiata Axis Rp 50.000',
                'denom' => '50000',
                'operator' => 'Axis',
                'price' => '49690',
                'status' => '0',
            ],
            [
                'id' => '7',
                'digital_id' => '1',
                'name' => 'Axiata Axis Rp 100.000',
                'denom' => '100000',
                'operator' => 'Axis',
                'price' => '99390',
                'status' => '0',
            ],
            [
                'id' => '8',
                'digital_id' => '1',
                'name' => 'Axiata Axis Rp 200.000',
                'denom' => '200000',
                'operator' => 'Axis',
                'price' => '198770',
                'status' => '0',
            ],
            [
                'id' => '9',
                'digital_id' => '1',
                'name' => 'Indosat Rp 5.000',
                'denom' => '5000',
                'operator' => 'Indosat',
                'price' => '6010',
                'status' => '0',
            ],
            [
                'id' => '10',
                'digital_id' => '1',
                'name' => 'Indosat Rp 10.000',
                'denom' => '10000',
                'operator' => 'Indosat',
                'price' => '11060',
                'status' => '0',
            ],
            [
                'id' => '11',
                'digital_id' => '1',
                'name' => 'Indosat Ooredoo Rp 20,000',
                'denom' => '20000',
                'operator' => 'Indosat',
                'price' => '20200',
                'status' => '0',
            ],
            [
                'id' => '12',
                'digital_id' => '1',
                'name' => 'Indosat Rp 25.000',
                'denom' => '25000',
                'operator' => 'Indosat',
                'price' => '25200',
                'status' => '0',
            ],
            [
                'id' => '13',
                'digital_id' => '1',
                'name' => 'Indosat Ooredoo Rp 30,000',
                'denom' => '30000',
                'operator' => 'Indosat',
                'price' => '29700',
                'status' => '0',
            ],
            [
                'id' => '14',
                'digital_id' => '1',
                'name' => 'Indosat Rp 50.000',
                'denom' => '50000',
                'operator' => 'Indosat',
                'price' => '49500',
                'status' => '0',
            ],
            [
                'id' => '15',
                'digital_id' => '1',
                'name' => 'Indosat Rp 100.000',
                'denom' => '100000',
                'operator' => 'Indosat',
                'price' => '97470',
                'status' => '0',
            ],
            [
                'id' => '16',
                'digital_id' => '1',
                'name' => 'Indosat Rp 150.000',
                'denom' => '150000',
                'operator' => 'Indosat',
                'price' => '144350',
                'status' => '0',
            ],
            [
                'id' => '17',
                'digital_id' => '1',
                'name' => 'Indosat Rp 200.000',
                'denom' => '200000',
                'operator' => 'Indosat',
                'price' => '189000',
                'status' => '0',
            ],
            [
                'id' => '18',
                'digital_id' => '1',
                'name' => 'Indosat Rp 250.000',
                'denom' => '250000',
                'operator' => 'Indosat',
                'price' => '234000',
                'status' => '0',
            ],
            [
                'id' => '19',
                'digital_id' => '1',
                'name' => 'Indosat Rp 500.000',
                'denom' => '500000',
                'operator' => 'Indosat',
                'price' => '467900',
                'status' => '0',
            ],
            [
                'id' => '20',
                'digital_id' => '1',
                'name' => 'Indosat Rp 1.000.000',
                'denom' => '1000000',
                'operator' => 'Indosat',
                'price' => '935000',
                'status' => '0',
            ],
            [
                'id' => '21',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 5.000',
                'denom' => '5000',
                'operator' => 'Smartfren',
                'price' => '5100',
                'status' => '0',
            ],
            [
                'id' => '22',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 10.000',
                'denom' => '10000',
                'operator' => 'Smartfren',
                'price' => '10000',
                'status' => '0',
            ],
            [
                'id' => '23',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 20.000',
                'denom' => '20000',
                'operator' => 'Smartfren',
                'price' => '19800',
                'status' => '0',
            ],
            [
                'id' => '24',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 25.000',
                'denom' => '25000',
                'operator' => 'Smartfren',
                'price' => '24750',
                'status' => '0',
            ],
            [
                'id' => '25',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 50.000',
                'denom' => '50000',
                'operator' => 'Smartfren',
                'price' => '49240',
                'status' => '0',
            ],
            [
                'id' => '26',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 60,000',
                'denom' => '60000',
                'operator' => 'Smartfren',
                'price' => '59090',
                'status' => '0',
            ],
            [
                'id' => '27',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 100.000',
                'denom' => '100000',
                'operator' => 'Smartfren',
                'price' => '97970',
                'status' => '0',
            ],
            [
                'id' => '28',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 150.000',
                'denom' => '150000',
                'operator' => 'Smartfren',
                'price' => '146960',
                'status' => '0',
            ],
            [
                'id' => '29',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 200.000',
                'denom' => '200000',
                'operator' => 'Smartfren',
                'price' => '195970',
                'status' => '0',
            ],
            [
                'id' => '30',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 250.000',
                'denom' => '250000',
                'operator' => 'Smartfren',
                'price' => '244940',
                'status' => '0',
            ],
            [
                'id' => '31',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 300.000',
                'denom' => '300000',
                'operator' => 'Smartfren',
                'price' => '293910',
                'status' => '0',
            ],
            [
                'id' => '32',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 500.000',
                'denom' => '500000',
                'operator' => 'Smartfren',
                'price' => '489850',
                'status' => '0',
            ],
            [
                'id' => '33',
                'digital_id' => '1',
                'name' => 'Smartfren Rp 1.000.000',
                'denom' => '1000000',
                'operator' => 'Smartfren',
                'price' => '979760',
                'status' => '0',
            ],
            [
                'id' => '34',
                'digital_id' => '1',
                'name' => 'Telkomsel Rp 5.000',
                'denom' => '5000',
                'operator' => 'Telkomsel',
                'price' => '5960',
                'status' => '0',
            ],
            [
                'id' => '35',
                'digital_id' => '1',
                'name' => 'Telkomsel Rp 10.000',
                'denom' => '10000',
                'operator' => 'Telkomsel',
                'price' => '10750',
                'status' => '0',
            ],
            [
                'id' => '36',
                'digital_id' => '1',
                'name' => 'Telkomsel Rp 20,000',
                'denom' => '20000',
                'operator' => 'Telkomsel',
                'price' => '22320',
                'status' => '0',
            ],
            [
                'id' => '37',
                'digital_id' => '1',
                'name' => 'Pulsa Telkomsel Rp25.000',
                'denom' => '25000',
                'operator' => 'Telkomsel',
                'price' => '25152',
                'status' => '0',
            ],
            [
                'id' => '38',
                'digital_id' => '1',
                'name' => 'Pulsa Telkomsel Rp 40.000',
                'denom' => '40000',
                'operator' => 'Telkomsel',
                'price' => '39720',
                'status' => '0',
            ],
            [
                'id' => '39',
                'digital_id' => '1',
                'name' => 'Pulsa Telkomsel Rp50.000',
                'denom' => '50000',
                'operator' => 'Telkomsel',
                'price' => '49900',
                'status' => '0',
            ],
            [
                'id' => '40',
                'digital_id' => '1',
                'name' => 'Pulsa Telkomsel Rp100.000',
                'denom' => '100000',
                'operator' => 'Telkomsel',
                'price' => '98232',
                'status' => '0',
            ],
            [
                'id' => '41',
                'digital_id' => '1',
                'name' => 'Pulsa Telkomsel Rp150.000',
                'denom' => '150000',
                'operator' => 'Telkomsel',
                'price' => '148000',
                'status' => '0',
            ],
            [
                'id' => '42',
                'digital_id' => '1',
                'name' => 'Pulsa Telkomsel Rp200.000',
                'denom' => '200000',
                'operator' => 'Telkomsel',
                'price' => '199000',
                'status' => '0',
            ],
            [
                'id' => '43',
                'digital_id' => '1',
                'name' => 'Pulsa Telkomsel Rp300.000',
                'denom' => '300000',
                'operator' => 'Telkomsel',
                'price' => '294860',
                'status' => '0',
            ],
            [
                'id' => '44',
                'digital_id' => '1',
                'name' => 'Pulsa Telkomsel Rp500.000',
                'denom' => '500000',
                'operator' => 'Telkomsel',
                'price' => '491430',
                'status' => '0',
            ],
            [
                'id' => '45',
                'digital_id' => '1',
                'name' => 'Pulsa Telkomsel Rp1000.000',
                'denom' => '1000000',
                'operator' => 'Telkomsel',
                'price' => '985380',
                'status' => '0',
            ],
            [
                'id' => '46',
                'digital_id' => '1',
                'name' => 'Tri Rp 1.000',
                'denom' => '1000',
                'operator' => 'Tri',
                'price' => '1217',
                'status' => '0',
            ],
            [
                'id' => '47',
                'digital_id' => '1',
                'name' => 'Tri Rp 2.000',
                'denom' => '2000',
                'operator' => 'Tri',
                'price' => '2229',
                'status' => '0',
            ],
            [
                'id' => '48',
                'digital_id' => '1',
                'name' => 'Tri Rp 5.000',
                'denom' => '5000',
                'operator' => 'Tri',
                'price' => '5471',
                'status' => '0',
            ],
            [
                'id' => '49',
                'digital_id' => '1',
                'name' => 'Tri Rp 8.000',
                'denom' => '8000',
                'operator' => 'Tri',
                'price' => '8167',
                'status' => '0',
            ],
            [
                'id' => '50',
                'digital_id' => '1',
                'name' => 'Tri Rp 10.000',
                'denom' => '10000',
                'operator' => 'Tri',
                'price' => '10536',
                'status' => '0',
            ],
            [
                'id' => '51',
                'digital_id' => '1',
                'name' => 'Tri Rp 15.000',
                'denom' => '15000',
                'operator' => 'Tri',
                'price' => '14900',
                'status' => '0',
            ],
            [
                'id' => '52',
                'digital_id' => '1',
                'name' => 'Tri Rp 20.000',
                'denom' => '20000',
                'operator' => 'Tri',
                'price' => '19800',
                'status' => '0',
            ],
            [
                'id' => '53',
                'digital_id' => '1',
                'name' => 'Tri Rp 25.000',
                'denom' => '25000',
                'operator' => 'Tri',
                'price' => '24750',
                'status' => '0',
            ],
            [
                'id' => '54',
                'digital_id' => '1',
                'name' => 'Tri Rp 30.000',
                'denom' => '30000',
                'operator' => 'Tri',
                'price' => '29690',
                'status' => '0',
            ],
            [
                'id' => '55',
                'digital_id' => '1',
                'name' => 'Tri Rp 50.000',
                'denom' => '50000',
                'operator' => 'Tri',
                'price' => '49490',
                'status' => '0',
            ],
            [
                'id' => '56',
                'digital_id' => '1',
                'name' => 'Tri Rp 100.000',
                'denom' => '100000',
                'operator' => 'Tri',
                'price' => '98980',
                'status' => '0',
            ],
            [
                'id' => '57',
                'digital_id' => '1',
                'name' => 'Tri Rp 150.000',
                'denom' => '150000',
                'operator' => 'Tri',
                'price' => '148470',
                'status' => '0',
            ],
            [
                'id' => '58',
                'digital_id' => '1',
                'name' => 'Tri Rp 200.000',
                'denom' => '200000',
                'operator' => 'Tri',
                'price' => '198230',
                'status' => '0',
            ],
            [
                'id' => '59',
                'digital_id' => '1',
                'name' => 'Tri Rp 300.000',
                'denom' => '300000',
                'operator' => 'Tri',
                'price' => '296940',
                'status' => '0',
            ],
            [
                'id' => '60',
                'digital_id' => '1',
                'name' => 'Tri Rp 500.000',
                'denom' => '500000',
                'operator' => 'Tri',
                'price' => '494900',
                'status' => '0',
            ],
            [
                'id' => '61',
                'digital_id' => '1',
                'name' => 'XL Rp 5.000',
                'denom' => '5000',
                'operator' => 'XL',
                'price' => '5930',
                'status' => '0',
            ],
            [
                'id' => '62',
                'digital_id' => '1',
                'name' => 'XL Rp 10.000',
                'denom' => '10000',
                'operator' => 'XL',
                'price' => '10960',
                'status' => '0',
            ],
            [
                'id' => '63',
                'digital_id' => '1',
                'name' => 'Axiata XL Rp 15.000',
                'denom' => '15000',
                'operator' => 'XL',
                'price' => '14910',
                'status' => '0',
            ],
            [
                'id' => '64',
                'digital_id' => '1',
                'name' => 'Axiata XL Rp 25.000',
                'denom' => '25000',
                'operator' => 'XL',
                'price' => '24850',
                'status' => '0',
            ],
            [
                'id' => '65',
                'digital_id' => '1',
                'name' => 'XL Rp 30.000',
                'denom' => '30000',
                'operator' => 'XL',
                'price' => '29640',
                'status' => '0',
            ],
            [
                'id' => '66',
                'digital_id' => '1',
                'name' => 'Axiata XL Rp 50.000',
                'denom' => '50000',
                'operator' => 'XL',
                'price' => '49690',
                'status' => '0',
            ],
            [
                'id' => '67',
                'digital_id' => '1',
                'name' => 'Axiata XL Rp 100.000',
                'denom' => '100000',
                'operator' => 'XL',
                'price' => '99390',
                'status' => '0',
            ],
            [
                'id' => '68',
                'digital_id' => '1',
                'name' => 'Axiata XL Rp 150.000',
                'denom' => '150000',
                'operator' => 'XL',
                'price' => '149080',
                'status' => '0',
            ],
            [
                'id' => '69',
                'digital_id' => '1',
                'name' => 'Axiata XL Rp 200.000',
                'denom' => '200000',
                'operator' => 'XL',
                'price' => '198770',
                'status' => '0',
            ],
            [
                'id' => '70',
                'digital_id' => '1',
                'name' => 'Axiata XL Rp 300.000',
                'denom' => '300000',
                'operator' => 'XL',
                'price' => '298160',
                'status' => '0',
            ],
            [
                'id' => '71',
                'digital_id' => '1',
                'name' => 'Axiata XL Rp 500.000',
                'denom' => '500000',
                'operator' => 'XL',
                'price' => '496930',
                'status' => '0',
            ],
            [
                'id' => '72',
                'digital_id' => '1',
                'name' => 'Axiata XL Rp 1.000.000',
                'denom' => '1000000',
                'operator' => 'XL',
                'price' => '993870',
                'status' => '0',
            ],
        ];

        $table = $this->table('digital_details');
        $table->insert($data)->save();
    }
}
